### ISSUE TITLE
ISO years: %G undocumented, and %Y may not translate correctly with %V

### ISSUE THREAD

**Issue by smemsh** [hroptatyr/dateutils#45]
was trying to get the Vulgar years/months/days for a full ISO year (to prepopulate some datafiles), using `dseq`, but there is no way to do it without `%G` (documented in `date.1` but not present in `dseq.1`):
```
 $ dateutils.dseq -i %Y%V%u -f '%Y %m %d %V %u' 20160101 20170101 | head
2015 01 04 01 01
2015 01 05 01 02
2015 01 06 01 03
2015 01 07 01 04
2016 01 08 01 05
2016 01 09 01 06
2016 01 10 01 07
2016 01 11 02 01
2016 01 12 02 02
2016 01 13 02 03
```

These are incorrect (discontiguous).  Instead %G is needed:
```
 $ dateutils.dseq -i %Y%V%u -f '%G %m %d %V %u' 20160101 20170101 | head
2016 01 04 01 01
2016 01 05 01 02
2016 01 06 01 03
2016 01 07 01 04
2016 01 08 01 05
2016 01 09 01 06
2016 01 10 01 07
2016 01 11 02 01
2016 01 12 02 02
2016 01 13 02 03
```

The output is correct / as intended.  So `%G` should be documented.  However, in this case I believe the input parsing is wrong, because the date `20160101` as `%Y%V%u` does not make sense, it should return an error due to ambiguity (mix of vulgar and ISO) and insist on `%G%V%u` as input format.  FWIW, these commands have identical outputs:

```
dateutils.dseq -i %Y%V%u -f '%G %m %d %V %u' 20160101 20170101
dateutils.dseq -i %G%V%u -f '%G %m %d %V %u' 20160101 20170101
```

(Note that I'm using the Debian version (0.3.1) but I scanned the v0.3.1..v0.3.5 git log and didn't find any relevant changes (and also `%G` itself was only present in the test suite for master branch))

**Comment by smemsh** [comment]
hmm, actually, I found out that the output is not correct anyways.  ISO date 2016-W01-1 is actually Vulgar 2015-12-27, so the output of `dateutils` appears to be just plain wrong:
```
 $ dconv -i %G%V%u -f %Y%m%d 20160101
20150104
```
This is almost certainly incorrect.  I tried with today's `master` branch.

**Comment by hroptatyr** [comment]
Hi Scott,
thanks for the report.  Yes, you're right.  The conversion to Gregorian years is wrong.

Re the `%G` issue, there's `%rY` to mean real years for calendric systems whose years differ from the Gregorian year, I imagine I put `%G` (and `%g`) as aliases for that.  I'll look into documenting these.

**Comment by hroptatyr** [comment]
The actual issue is fixed in e25822d, the docfix is in 3600939.

**Comment by smemsh** [comment]
I just refreshed my clone and retried the aforementioned test.  The output is
indeed different, but still incorrect:

```
 $ dateutils.dconv -i %G%V%u -f %Y%m%d 20160101 # old code
20150104

 $ dconv -i %G%V%u -f %Y%m%d 20160101 # new code
20160104
```

I do not think this is fixed:

- input format `%G%V%u` for 20160101 says first day of first ISO week in ISO
  year 2016
- output format says: "what's the corresponding Vulgar YYYYMMDD?"

unless I'm misunderstanding how this is supposed to work, the output should be
`20151227`.

I used http://www.timeanddate.com/date/weeknumber.html#!week=01&year=2016 to
get the correct date.

**Comment by hroptatyr** [comment]
The first ISO week of the year is the first week that contains the first of January and has at least 4 days, alternatively and equivalently you could say it's the week that contains the first Thursday, cf. https://en.wikipedia.org/wiki/ISO_week_date#First_week

Note: There are also other numbering schemes in place, like the one you pointed out.  There are no plans to support these because they're a nuisance to specify via format specifiers or with parameters in the command line (see GNU's `gcal -hh` for a good scare).  They might be useful for stateful applications, i.e. where you could set your preference in a config file.

**Comment by hroptatyr** [comment]
Now having had a look at the timeanddate website, how did you expect 2015-12-27 to be the first day of the first week?  First it's a Sunday, ISO weeks start on Monday, and related to that, if weeks start on Monday, 2015-12-27 is 2 weeks before the first 2016 ISO week.

It really puzzles me how you came up with that date :)

**Comment by smemsh** [comment]
I had actually read that article, but failed to double check the output from
the website... To come up with 2015-12-27, all I did was plug in week 1 year
2016 and selected "calculate dates."  It outputs the start date as Dec 27,
2015 (which, I see now is wrong).  I also had seen a 2004-W01-1 example
previously (that starts in 2003), demonstrating start in previous year, and
just assumed the math on the page was correct; it passed my feasibility
heuristics :-)

At least a real bug got fixed in dateutils :-) If prehaps by a haphazard
route.

FWIW, I manually verified all the ones just now from the table on the
Wikipedia page:

```
vulfmt=%Y-%m-%d
isofmt=%G-W%V-%u

table=(
        2005-01-01      2004-W53-6
        2005-01-02      2004-W53-7
        2005-12-31      2005-W52-6
        2007-01-01      2007-W01-1
        2007-12-30      2007-W52-7
        2007-12-31      2008-W01-1
        2008-01-01      2008-W01-2
        2008-12-28      2008-W52-7
        2008-12-29      2009-W01-1
        2008-12-30      2009-W01-2
        2008-12-31      2009-W01-3
        2009-01-01      2009-W01-4
        2009-12-31      2009-W53-4
        2010-01-01      2009-W53-5
        2010-01-02      2009-W53-6
        2010-01-03      2009-W53-7
)

while ((i < ${#table}))
do      
        vul=${table[i++]}
        iso=${table[i++]}
        vul2iso=$(dconv -i $vulfmt -f $isofmt $vul)
        iso2vul=$(dconv -i $isofmt -f $vulfmt $iso)
        [[ $vul2iso == $iso ]] || exit 5
        [[ $iso2vul == $vul ]] || exit 10
done
```

The exit was clean.

**Comment by smemsh** [comment]
btw, agreed on the "other numbering schemes."  Yes, I've seen the `gcal` in-program docs before and ran away in horror... actually, it's what originally drove me to find dateutils :-) But I do think removing the zero-pad on the `%u` was the right choice because that at least allows creating one in the standard format with a simple static format string.

(another possibility is maybe `%02u` ala `printf(3)` if you wanted `01` instead of `1`)

In any case, this utility makes my life so much easier.  Thanks!
